
[Env]
# enums  dev test prod
GoEnv = "local"

[Dapr]
PubsubName = "pubsub"
DaprCmdSubTopic = "car.cmd.down"

[Redis]
Addr = "39.99.174.39:7379"
Password = "pay.Media@2020#redis"
DB = 0

[MySQL]
Type = "mysql"
User = "sa"
Password = "qWSxBNqb"
Host = "rm-8vbjy34g96075qpoklo.mysql.zhangbei.rds.aliyuncs.com:3408"
DBName = "car_broke"
Debug = "true"
